service: ginyu

provider:
  name: aws
  runtime: python3.6
  stage: dev
  region: ap-northeast-1
  iamRoleStatements:
    - Effect: "Allow"
      Action: 
        - "s3:PutObject"
        - "s3:PutObjectAcl"
        - "s3:*"
      Resource: "arn:aws:s3:::*"
  timeout: 60

functions:
  hello:
    handler: handler.resize
    events:
      - s3:
          bucket: tirashi
          event: s3:ObjectCreated:*

# you can add CloudFormation resource templates here
resources:
  Resources:
    NewResource:
      Type: "AWS::S3::Bucket"
      Properties:
        BucketName: tirashi-resize

